### ISSUE TITLE
IDEA

### ISSUE THREAD

**Issue by PatrykKuniczak** [PatrykKuniczak/YT_Notifier#1]
Main idea is create plugin which check on browser start, if something new is released on YouTube from subscribed value by user.

Checking if video titile contain this subscribed word.

E.g User want to check if something new with keyword "Baby Shark" in title is released since last check.

This subscribed word has been entered by user and stored for use in future browser opens.

Features v1.0.0:
- [x] Store subscibed words for check #77
- [x] On startup browser, check once if the stored value for search have something new #78
- [x] Create button "Watch Later" near fetched video, and after click this video is saved on "Watch Later" playlist #73
- [x] On click "Watch Later" button on navbar section, user is directed upon his playlist #73 
- [x] Don't logout user on close browser/log in automatticaly on browser start #42 #6
- [x] Searching fetched videos by title #30
- [x] When user is logout by session is expired, create notification with that info and suggest to log in again #67
